FROM node:19.6-bullseye-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && npm ci 

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.23-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080
