# Ghim version và sử dụng Debian bản slim để tối ưu hơn
FROM node:19.6-bullseye-slim AS builder

WORKDIR /app

# Copy các phụ thuộc
COPY package-lock.json* package.json ./

# Cài đặt các phụ thuộc và cache để build lại nhanh hơn
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && npm ci 

# Node có sẵn group/user node gid/uid 1000 rồi
COPY --chown=node:node ./healthcheck . 

COPY --chown=node:node ./src .

USER node 

EXPOSE 5000

ENTRYPOINT ["node"]

CMD ["index.js"]



